name: Tests

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ['3.8', '3.9', '3.10']
    steps:

    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        pip install -U -r requirements.txt
        pip install -U -r requirements_backend.txt
        pip install -U -e .[cssselect,pyquery]

    - name: Run tests
      run: |
        coverage run runtest.py --test-all
        coverage lcov .coverage.lcov

    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: ./.coverage.lcov
        flag-name: run-${{ matrix.os }}-${{ python }}
        parallel: true 

  finish:
      needs: test
      runs-on: ubuntu-latest
      steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: ./.coverage.lcov
          parallel-finished: true
